name = "hoang-editor-auto-post"
main = "worker.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["0 12 * * *", "0 16 * * *", "0 0 * * *", "0 8 * * 1"]

[[r2_buckets]]
bucket_name = "hoang-editor-images"
binding = "BLOG_IMAGES"

[ai]
binding = "AI"
